# Generated by Django 4.2 on 2025-12-14 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('groq', 'Groq')], max_length=20)),
                ('description', models.TextField()),
                ('use_cases', models.TextField(help_text='Comma-separated use cases')),
                ('strength', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModelFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.aimodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='selected_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.aimodel'),
        ),
        migrations.AddField(
            model_name='message',
            name='model_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.aimodel'),
        ),
        migrations.CreateModel(
            name='ModelUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('prompt_count', models.IntegerField(default=0)),
                ('last_feedback_at', models.IntegerField(default=0, help_text='Prompt count when last feedback was requested')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.aimodel')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('session_key', 'model')},
            },
        ),
    ]
