# Generated by Django 4.2 on 2025-12-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_previouspaper_questionpaper_generatedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
