# Generated by Django 4.2 on 2025-12-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_chat_user_document_uploaded_by_learningitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('groq', 'Groq'), ('gpt', 'OpenAI GPT'), ('local', 'Local Model')], max_length=20),
        ),
    ]
